apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: production
data:
  prometheus.yml: |
    scrape_configs:
    - job_name: 'production-service'
      scrape_interval: 5s
      static_configs:
        - targets: ['devops-service:8081']
    rule_files:
    - /etc/prometheus/alerts/alert_rules.yml
  alert_rules.yml: |
    groups:
    - name: Job down alert
      rules:
      - alert: JobDown
        expr: up{job="production-service"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Job has been down for more than 5 minutes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.45.3
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
            - name: prometheus-alert-rules-volume
              mountPath: /etc/prometheus/alerts/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-config
        - name: prometheus-storage-volume
          emptyDir: {}
        - name: prometheus-alert-rules-volume
          configMap:
            defaultMode: 420
            name: prometheus-config
            items:
            - key: alert_rules.yml
              path: alert_rules.yml
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: production
spec:
  selector: 
    app: prometheus-server
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090