metadata:
  name: supercool
  namespace: production
  labels:
    name: supercool

replicaCount: 1

image:
  repository: supercool-docker
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: lastest

deploymentPort:
  containerPort: 8080

service:
  name: devops-service
  type: LoadBalancer
  port: 80
  targetPort: 8080
  selector:
    app: devops
    tier: project
